#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

#define RTE_DEVICE_STDPERIPH_CRC
#define RTE_DEVICE_STDPERIPH_DMA
#define RTE_DEVICE_STDPERIPH_FLASH
#define RTE_DEVICE_STDPERIPH_GPIO
#define RTE_DEVICE_STDPERIPH_RCC
#define RTE_DEVICE_STDPERIPH_USART
#define RTE_DEVICE_STDPERIPH_FRAMEWORK

#endif
